// Import global styles and required components/providers
import "./globals.css";
import Providers from './provider';
import { NavBar } from "./components/NavBar";
import { CartProvider } from "./components/CartContext";
import { Footer } from "./components/Footer";

// Metadata for the app, defining the title and description
export const metadata = {
    title: "Crooked Clothing",
    description: "Generated by create next app",
};

// RootLayout component - Wraps the entire application with shared elements
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                {/* Adobe Fonts Embed Link */}
                <link rel="stylesheet" href="https://use.typekit.net/xwa5mii.css" />
            </head>
            <body>
                {/* Providers wrap the application to provide global state and context */}
                <Providers>
                    <CartProvider>
                        <NavBar />
                        
                        {children}
                        
                        <Footer />
                    </CartProvider>
                </Providers>
            </body>
        </html>
    );
}
